### PR TITLE
Message now returns an instance of `\DateTimeImmutable`

### LINKED ISSUE #7: Message::getTimestamp() return type ambiguous
https://github.com/hellofresh/reagieren/blob/master/src/Message.php#L34

I think we should have more guarantees of what this returns. Either an instance of `DateTime` or, to keep it a string, at least format it in ISO_8601.

### PR DESCRIPTION
**Pull request by kieranajp**
Fixes #7

### CODE REVIEW

**Comment by italolelis** [comment]
Can we have some tests for this?

**Comment by kieranajp** [comment]
Sure - we don't have any tests at all just now (!) so need to spend some time adding them throughout really.

**Comment by italolelis** [comment]
Just add mock tests for this part :D

**Comment by kieranajp** [comment]
^

**Pull request merged**
